### ISSUE TITLE
https://github.com/zack-bitcoin/amoveo/blob/master/docs/progress_reports/February_2018.md

### ISSUE THREAD

**Issue by okdoomfist** [zack-bitcoin/amoveo#101]
Following links are broken:
https://github.com/zack-bitcoin/amoveo/blob/master/tests/test_market.py
https://github.com/zack-bitcoin/amoveo/blob/master/apps/ae_core/src/consensus/txs/test_txs.erl
https://github.com/zack-bitcoin/amoveo/blob/master/apps/ae_core/src/consensus/txs/test_txs.erl
https://github.com/zack-bitcoin/amoveo/blob/master/tests/test_lightning.py
https://github.com/zack-bitcoin/amoveo/blob/master/tests/test_market.py

**Comment by zack-bitcoin** [comment]
great. thank you for pointing this out.

**Comment by zack-bitcoin** [comment]
I fixed the dead links.
