### ISSUE TITLE
keys:pubkey() displays public key in  non-standard form

### ISSUE THREAD

**Issue by burjorjee** [zack-bitcoin/amoveo#102]
The format of the public key displayed by keys:pubkey() does not match the format of the public key on line 8 of miner.erl. How does one determine one's public key?

```
> keys:pubkey().
<<4,19,71,199,168,161,119,50,86,241,29,167,52,82,65,74,
  134,46,104,6,115,56,194,90,228,250,114,37,99,...>>
```

**Comment by zack-bitcoin** [comment]
api:pubkey().
