### ISSUE TITLE
getting ready for the real deal

### ISSUE THREAD

**Issue by McKean** [zack-bitcoin/amoveo#103]
Just some questions I have, and maybe it would help others preparing for live network.

What steps should we take to make the chain run live?  
Change this to false?  
https://github.com/zack-bitcoin/amoveo/blob/1e245e0913580093a75c12579fc92239fe9f6d02/config/sys.config.tmpl#L10  

Also when starting a chain is there a key/wallet assigned automatically? Is there a way to predefine this wallet/key?  
https://github.com/zack-bitcoin/amoveo/blob/1e245e0913580093a75c12579fc92239fe9f6d02/config/sys.config.tmpl#L8  
Would that be the place, or is this the master key to synv with?

When mining should we use a new key or is it good practice to use the key genrated/used from the blockchain instance?

Sorry if these questions sound noobish

Thanks, and looking forward to this.

**Comment by zack-bitcoin** [comment]
No, don't mess with the test_mode line. it is already set to false in the Makefile when you build the production node.
besides, that line is above this line: https://github.com/zack-bitcoin/amoveo/blob/1e245e0913580093a75c12579fc92239fe9f6d02/config/sys.config.tmpl#L17

If you don't have a key, then your node generates one and stores it in `_build/prod/rel/amoveo_core/keys/keys.db`.

You can save this keys.db folder or put it into a different node.

it doesn't matter what key you use for mining, but it is probably more secure to generate your key in erlang than javascript. It is even more secure to generate the key off-line in cold storage.

**Comment by McKean** [comment]
Thanks for the quick reply.
So how can I get the node into production? Will it then standby and wait for whatever you need to make happen?

So I guess I'll have the blockchain node use whatever key and generate one separately.

**Comment by zack-bitcoin** [comment]
I will try to push the code to github at exactly 11:00 AM GMT.
So do a `git pull` after that moment.
I will write announcements on telegram/reddit/twitter that we are starting.
