### ISSUE TITLE
Not automatically syncing

### ISSUE THREAD

**Issue by McKean** [zack-bitcoin/amoveo#113]
Maybe I'm doing something wrong but bascially doing a.

```
sync:start().
% Waiting for all blocks to be synced
sync_mode:normal().
```
To make get it to be aware of new blocks I need to manually execute `sync:get_headers({{159,89,106,253}, 8080}).`

Any ideas what the issue is?

Thanks!

**Comment by zack-bitcoin** [comment]
Thank you for sharing this issue.
I will try and make a fix soon.

**Comment by termoose** [comment]
Having a similar issue, one fix (that should not be final) could be to have something like:

```erlang
handle_info(sync_cron, _From, State) ->
    sync:get_headers({{159,89,106,253}, 8080}),
    sync:start(),
    self() ! sync_cron,
    {noreply, State}.
```

Any better solution on the horizon?

**Comment by zack-bitcoin** [comment]
https://github.com/zack-bitcoin/amoveo/blob/master/docs/getting-started/sync.md
here are notes on syncing for anyone else having similar problems.

**Comment by touzi** [comment]
I also met the same problem.
sync:start().
sync_mode:normal().
Operation after a stay in 13896 the block level.
peers:all().
After operation, only a few addresses.

I tried the new synchronization, do the following steps
make prod-stop
make prod-clean
make prod-restart
Still no real-time data synchronization

**Comment by Sykh** [comment]
It only syncs automaticly if your IP is reachable from the outside, the node never pulls on itself but is waiting for push notifications.

If you aren't reachable you have to run sync:start(). every now and then or just use a light wallet.
