### ISSUE TITLE
Tests Crash logs

### ISSUE THREAD

**Issue by cynic89** [zack-bitcoin/amoveo#124]
Found the following crash logs while running multi node tests:

Generic server tx_pool_feeder terminating
** Last message in was {'$gen_cast',{absorb,{signed,{ctc,<<4,133,89,134,205,122,130,218,16,254,229,12,186,57,121,105,43,173,164,137,130,226,246,188,49,236,32,10,247,161,232,193,46,14,58,3,190,212,42,97,158,69,121,135,20,133,143,208,46,58,66,6,181,227,170,244,237,22,35,120,150,45,13,134,58>>,<<4,84,99,184,40,46,117,36,209,83,191,82,86,128,129,189,104,185,231,227,117,65,235,97,189,2,58,44,165,2,160,67,199,188,135,222,118,68,11,198,123,131,217,82,71,170,130,235,80,185,151,201,236,81,90,205,172,57,60,50,46,199,114,47,225>>,152118,9,<<189,88,82,4,136,206,237,245,52,87,139,244,241,97,246,59,103,43,130,59,101,247,4,206,14,226,36,250,55,129,216,211>>,-3208},<<48,69,2,32,103,119,252,183,78,192,209,2,250,239,201,113,53,200,80,84,241,40,112,228,175,71,114,158,220,136,97,81,75,139,225,218,2,33,0,231,160,243,111,22,24,73,213,15,181,219,161,88,150,18,83,217,244,164,50,164,67,134,67,213,217,198,236,9,170,223,96>>,<<48,70,2,33,0,221,219,162,6,193,187,225,165,155,225,178,18,108,47,234,68,67,116,238,213,17,27,251,112,210,222,239,149,51,58,42,77,2,33,0,240,161,119,83,202,9,190,35,86,38,65,82,12,244,243,174,108,216,32,218,69,75,129,58,12,184,37,168,19,252,132,201>>}}}
** When Server state == []
** Reason for termination ==
** {{badrecord,channel},[{channels,closed,1,[{file,"/home/shysank/code/amoveo/_build/dev1/lib/amoveo_core/src/consensus/trees/channels.erl"},{line,31}]},{channel_team_close_tx,go,3,[{file,"/home/shysank/code/amoveo/_build/dev1/lib/amoveo_core/src/consensus/txs/channel_team_close_tx.erl"},{line,43}]},{txs,digest_from_dict3,3,[{file,"/home/shysank/code/amoveo/_build/dev1/lib/amoveo_core/src/consensus/txs/txs.erl"},{line,14}]},{tx_pool_feeder,absorb_unsafe,4,[{file,"/home/shysank/code/amoveo/_build/dev1/lib/amoveo_core/src/consensus/tx_pool_feeder.erl"},{line,139}]},{tx_pool_feeder,handle_cast,2,[{file,"/home/shysank/code/amoveo/_build/dev1/lib/amoveo_core/src/consensus/tx_pool_feeder.erl"},{line,19}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,616}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,686}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2018-03-14 22:32:11 =CRASH REPORT====
  crasher:
    initial call: tx_pool_feeder:init/1
    pid: <0.1218.0>
    registered_name: tx_pool_feeder
    exception error: {{badrecord,channel},[{channels,closed,1,[{file,"/home/shysank/code/amoveo/_build/dev1/lib/amoveo_core/src/consensus/trees/channels.erl"},{line,31}]},{channel_team_close_tx,go,3,[{file,"/home/shysank/code/amoveo/_build/dev1/lib/amoveo_core/src/consensus/txs/channel_team_close_tx.erl"},{line,43}]},{txs,digest_from_dict3,3,[{file,"/home/shysank/code/amoveo/_build/dev1/lib/amoveo_core/src/consensus/txs/txs.erl"},{line,14}]},{tx_pool_feeder,absorb_unsafe,4,[{file,"/home/shysank/code/amoveo/_build/dev1/lib/amoveo_core/src/consensus/tx_pool_feeder.erl"},{line,139}]},{tx_pool_feeder,handle_cast,2,[{file,"/home/shysank/code/amoveo/_build/dev1/lib/amoveo_core/src/consensus/tx_pool_feeder.erl"},{line,19}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,616}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,686}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors: [testnet_sup,<0.919.0>]
    message_queue_len: 0
    messages: []

2018-03-14 22:32:06 =ERROR REPORT====
** Generic server tx_pool_feeder terminating
** Last message in was {absorb,{signed,{create_acc_tx,<<4,133,89,134,205,122,130,218,16,254,229,12,186,57,121,105,43,173,164,137,130,226,246,188,49,236,32,10,247,161,232,193,46,14,58,3,190,212,42,97,158,69,121,135,20,133,143,208,46,58,66,6,181,227,170,244,237,22,35,120,150,45,13,134,58>>,6,152118,<<4,71,92,5,229,124,201,119,36,139,251,54,46,77,154,38,128,134,231,223,252,219,38,156,32,167,88,73,111,185,167,166,90,132,54,104,33,73,206,136,14,253,209,216,247,42,195,82,194,7,106,171,82,250,32,245,57,109,202,184,250,233,6,10,2>>,1000000000},<<48,69,2,32,116,199,234,234,108,146,76,231,156,195,189,10,95,240,140,198,225,22,163,30,167,134,155,146,218,113,156,193,230,149,149,146,2,33,0,136,175,98,252,199,255,18,193,222,79,22,208,204,7,71,193,74,210,168,100,50,224,222,91,234,146,26,203,117,201,122,171>>,[]}}
** When Server state == []
** Reason for termination ==
** {{badmatch,{acc,999914000,1,<<4,71,92,5,229,124,201,119,36,139,251,54,46,77,154,38,128,134,231,223,252,219,38,156,32,167,88,73,111,185,167,166,90,132,54,104,33,73,206,136,14,253,209,216,247,42,195,82,194,7,106,171,82,250,32,245,57,109,202,184,250,233,6,10,2>>,0,<<7,106,39,199,158,90,206,42,61,71,249,221,46,131,228,255,110,168,135,43,60,34,24,246,108,146,184,155,85,243,101,96>>}},[{create_account_tx,go,3,[{file,"/home/shysank/code/amoveo/_build/dev1/lib/amoveo_core/src/consensus/txs/create_account_tx.erl"},{line,41}]},{txs,digest_from_dict3,3,[{file,"/home/shysank/code/amoveo/_build/dev1/lib/amoveo_core/src/consensus/txs/txs.erl"},{line,14}]},{tx_pool_feeder,absorb_unsafe,4,[{file,"/home/shysank/code/amoveo/_build/dev1/lib/amoveo_core/src/consensus/tx_pool_feeder.erl"},{line,139}]},{tx_pool_feeder,handle_call,3,[{file,"/home/shysank/code/amoveo/_build/dev1/lib/amoveo_core/src/consensus/tx_pool_feeder.erl"},{line,10}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,636}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,665}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
** Client <0.1168.0> stacktrace
** [{gen,do_call,4,[{file,"gen.erl"},{line,169}]},{gen_server,call,2,[{file,"gen_server.erl"},{line,202}]},{tx_pool_feeder,absorb,1,[{file,"/home/shysank/code/amoveo/_build/dev1/lib/amoveo_core/src/consensus/tx_pool_feeder.erl"},{line,148}]},{ext_handler,doit,1,[{file,"/home/shysank/code/amoveo/_build/dev1/lib/amoveo_http/src/ext_handler.erl"},{line,114}]},{ext_handler,handle,2,[{file,"/home/shysank/code/amoveo/_build/dev1/lib/amoveo_http/src/ext_handler.erl"},{line,34}]},{cowboy_handler,handler_handle,4,[{file,"/home/shysank/code/amoveo/_build/default/lib/cowboy/src/cowboy_handler.erl"},{line,111}]},{cowboy_protocol,execute,4,[{file,"/home/shysank/code/amoveo/_build/default/lib/cowboy/src/cowboy_protocol.erl"},{line,442}]}]

**Comment by zack-bitcoin** [comment]
This seems to be happening with the market.py test.
these errors are because nodes are trying to share txs that they have already shared with each other.
