### ISSUE TITLE
change_password does not change the password

### ISSUE THREAD

**Issue by stephanschielke** [zack-bitcoin/amoveo#127]
On a new node:

`> keys:lock().                         
ok
> keys:status().
locked
> keys:unlock("").
ok
> keys:status().  
unlocked
> keys:change_password("", "foobar").
keys diedok
start keys
> keys:status().                     
locked
> keys:unlock("").                   
ok
> keys:status().  
unlocked
> 
`

The default password still unlocks the keys. I'd expect change_password to change the password to "foobar" in this case. No error is indicated.

**Comment by zack-bitcoin** [comment]
"keys died" is the error message. 
Thank you for sharing this error. We will take care of it soon.

**Comment by Sykh** [comment]
This is fixed afaik.

**Comment by zack-bitcoin** [comment]
Yes. Thanks for mentioning.
