### ISSUE TITLE
Update linux_dependencies.md

### ISSUE THREAD

**Issue by rby123** [zack-bitcoin/amoveo#14]
In the After Dependencies section, should be cd amoveo not cd testnet

**Comment by zack-bitcoin** [comment]
Hard to tell what you mean. I removed some aeternity references just now.

**Comment by breakthroughsecurity** [comment]
I had the same problem rby123 had.  on this page https://github.com/zack-bitcoin/amoveo/blob/master/docs/getting-started/linux_dependencies.md  at the very bottom......

Now you can go into the directory, and compile the Amoveo testnet.

cd testnet/
make prod-build

it shoud be 

cd amoveo/
make prod-build
