### ISSUE TITLE
节点运行几天后 block 高度与 api 高度不同 

### ISSUE THREAD

**Issue by touzi** [zack-bitcoin/amoveo#147]
我的节点运行了几天都很正常, 今天早上发现 block 高度与 api 高度不同. 

![image](https://user-images.githubusercontent.com/3685924/39659059-95274b8e-5052-11e8-8ca5-931c5e1080c8.png)

api 高度是同步的, block 高度没有同步. 然后我今天通过 make prod-restart 重启了节点, 貌似也没有开始同步 block , 我需要在观察一段时间

**Comment by touzi** [comment]
我继续尝试输入 sync:start(). 然后开始同步了, 但为什么 block 会自动停止同步?

**Comment by zack-bitcoin** [comment]
I think you need `sync_mode:normal().`

Also good to do `keys:unlock("").`

I wrote about them here: https://github.com/zack-bitcoin/amoveo/blob/master/docs/getting-started/sync.md

Also, your node needs to have externally accessible IP address so that the other nodes can send messages to you.
