### ISSUE TITLE
keys:id().  and keys:address().  do not seem to work

### ISSUE THREAD

**Issue by breakthroughsecurity** [zack-bitcoin/amoveo#15]
(ae_core_prod@ivi3t4l-VirtualBox)32> api:balance().
3598233513
(ae_core_prod@ivi3t4l-VirtualBox)33> keys:id().
** exception error: undefined function keys:id/0
(ae_core_prod@ivi3t4l-VirtualBox)34> keys:pubkey().
<<4,79,113,118,99,248,182,217,226,159,200,119,192,217,46,
  207,144,167,176,123,138,230,182,208,29,191,192,70,116,
  ...>>
(ae_core_prod@ivi3t4l-VirtualBox)35> keys:address().
** exception error: undefined function keys:address/0
(ae_core_prod@ivi3t4l-VirtualBox)36>

**Comment by zack-bitcoin** [comment]
Those functions no longer exist.
They should be removed from the documentation.
Thank you for pointing this out.

**Comment by damoCl** [comment]
Are there alternatives for these commands. 

A simple example, of sending money from one account to another would be really helpful.

**Comment by zack-bitcoin** [comment]
https://github.com/zack-bitcoin/amoveo/blob/master/tests/test_spend.py

Here is an example of credit an account and sending it money.

**Comment by zack-bitcoin** [comment]
https://github.com/zack-bitcoin/amoveo/blob/master/tests/test_spend.py

Here is an example of creating an account and sending it money.
