### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Coryvmcs1** [zack-bitcoin/amoveo#151]
===> Verifying dependencies...
===> Skipping pink_hash (from {git,
                                      "https://github.com/BumblebeeBat/pink_crypto",
                                      {branch,"partial_hash_problem"}}) as an app of the same name has already been fetched
===> Compiling jiffy
===> Compiling /root/amoveo/_build/default/lib/jiffy/c_src/*.c
===> cc: fatal error: cannot specify -o with -c, -S or -E with multiple files
compilation terminated.

Makefile:135: recipe for target 'build' failed

**Comment by zack-bitcoin** [comment]
do not run amoveo as root.
