### ISSUE TITLE
bad password gives a non descriptive error

### ISSUE THREAD

**Issue by breakthroughsecurity** [zack-bitcoin/amoveo#16]
if an incorrect password is given the error that comes back is not clear on what happened.  
(ae_core_prod@ivi3t4l-VirtualBox)47> keys:unlock("a").
ok
(ae_core_prod@ivi3t4l-VirtualBox)48> keys diedstart keys

**Comment by zack-bitcoin** [comment]
Great. Thank you for pointing this out.

**Comment by zack-bitcoin** [comment]
I think we need to modify encryption.erl to fix this.
We should do term_to_bin and bin_to_term in encryption.erl, we should only deal with binaries instead.

**Comment by zack-bitcoin** [comment]
https://github.com/zack-bitcoin/amoveo/commit/198a214a97a372d5a5a72925e03892690a8f014a

Here is a hackish fix.
When keys dies, we will post a message about how a bad password might have caused a failure.
