### ISSUE TITLE
Docs missing for multi tx

### ISSUE THREAD

**Issue by tallakt** [zack-bitcoin/amoveo#170]
https://github.com/zack-bitcoin/amoveo/blob/master/docs/design/transaction_types.md

**Comment by okdoomfist** [comment]
This seems important. I searched the telegram for examples, but didn't find it. Should be a 2 min fix.

**Comment by zack-bitcoin** [comment]
Thanks for the suggestion. Here is the commit to fix it: https://github.com/zack-bitcoin/amoveo/commit/8ab50e6c4c7196f76b783741f6fe3952dd8fe4c2
