### ISSUE TITLE
LOGOTYPE PROPOSAL FOR AMOVEO

### ISSUE THREAD

**Issue by orlant** [zack-bitcoin/amoveo#171]
Hi, I'm a graphic designer and I like to make contributions in projects like this that do not have a logo yet. If you allow me, can I create one for your repository?

**Comment by okdoomfist** [comment]
Amoveo has working logos, but I'm sure the community would like to see what you may come up with :smile:

**Comment by okdoomfist** [comment]
Probably ok to close this

**Comment by orlant** [comment]
if friend is unfortunately the best since I need the authorization of the owner. anyway it's good that they already have their logo
