### ISSUE TITLE
Wallet/Explorer improvements

### ISSUE THREAD

**Issue by ghost** [zack-bitcoin/amoveo#173]
**1. Link light node wallet.html to explorer.html on same node, and vice versa.**

**2. On mainstream wallets SEND is SEND NOW:**
Solution: Spend or Send on most wallets "signs and broadcasts" the transaction, and should be default behaviour. The other option ("unsigned spend") is the less commonly used feature, and should be the more descriptive one. E.g. "generate transaction, but do not sign or send". This will reduce confusion. 

**3. Copying and pasting recipient address with trailing space or period is a common problem:**
When a sending a tx, the "to pubkey:" field should automatically parse for spaces and newline characters (or any other common noise, such as `.` at the end of the address due to workerID. It should parse for the B and = characters and/or length for the beginning and end of the address. 

**4. Maximum amount is a common feature on modern wallets:**
There should be a "maximum amount" button. This is similar to the "send all your veo to this address" button, but in a safer, more common implementation. Requires: pubkey field to be filled because maximum amount depends on fee, which depends on new/existing account.
 - if pubkey field is not filled, display message, "please input recipient address."
 - "send" button must still be pressed to complete the transaction, the "maximum amount" button merely populates the "amount to send" field.

**5. When sending a tx fails, there should be detailed feedback as to why it has failed:**
 - You do not have this much veo. Your balance is: x
 - Load your keys and check your balance first
 - You do not have enough veo to cover the fee, use the maximum amount button to populate the amount field
 - This is not a valid recipient address
 - or whatever is the appropriate reason, in a low level and user oriented language

**6. When a send succeeds, this should be detailed as well:**
 - Your tx [hash] for x Veo has been sent to B...= and is in the txpool. Your balance after transaction. Their balance after transaction. [Button to see if tx was included in a block or is still in txpool]. z confirmations. 

**7. Steps should be taken to reduce clutter on light wallet:**
Accordion style elements defaulting to only wallet features visible would go a long way for new users not feeling overwhelmed in a cluttered utilitarian interface. They can explore/expand other features once they are comfortable with the wallet. None of the other features are worthwhile if they cannot save/load keys and send veo.

This is based on my experience helping people 1 on 1 with simple transactions and trades. Please discuss.

**Comment by okdoomfist** [comment]
Other ideas:
**8. Can node "know" if it's on an old fork and report that it is not topheight?** 

**9. Display balance immediately upon loading keys.**

**Comment by zack-bitcoin** [comment]
These are all great ideas.

8) yes we can do that.

**Comment by zack-bitcoin** [comment]
suggestion (1) completed. https://github.com/zack-bitcoin/amoveo/commit/271d020a26122f3b7ba28600dca22d4c2c683b1a

**Comment by zack-bitcoin** [comment]
suggestion (2) completed. https://github.com/zack-bitcoin/amoveo/commit/2efdb1c2791a50eeb21772a3b6b47a6744c2133a

**Comment by zack-bitcoin** [comment]
suggestion (3) completed. https://github.com/zack-bitcoin/amoveo/commit/754f4ddadbe930f067ddd7dce0641bc9ab7c513a

**Comment by zack-bitcoin** [comment]
suggestion (4) completed. https://github.com/zack-bitcoin/amoveo/commit/ef5569302496cec0760deddda5c8f5f60748e907

**Comment by zack-bitcoin** [comment]
suggestion (9) complete.  https://github.com/zack-bitcoin/amoveo/commit/e3ffc3e966c1feab3328191a2060f91da0b57f02

**Comment by zack-bitcoin** [comment]
suggestion (4) wasn't working before. now it is https://github.com/zack-bitcoin/amoveo/commit/a71a5ddc2e1c26d3098f8b9abf923eed8bb2b18a
