### ISSUE TITLE
unused python dependencies 

### ISSUE THREAD

**Issue by zack-bitcoin** [zack-bitcoin/amoveo#185]
we should remove unused dependencies from requirements.txt
It seems like none are being used.

**Comment by okdoomfist** [comment]
Are python dependencies for running tests?

**Comment by okdoomfist** [comment]
Perhaps they could be added here instead https://github.com/zack-bitcoin/amoveo/blob/master/docs/merging-and-testing/testing.md

**Comment by zack-bitcoin** [comment]
They were for tests at one point. I think it is completely unused now.
