### ISSUE TITLE
Setup Video Tutorial

### ISSUE THREAD

**Issue by eolszewski** [zack-bitcoin/amoveo#187]
Running a local test node is a bit lackluster following [these instructions](https://github.com/zack-bitcoin/amoveo/blob/master/docs/getting-started/build_intro.md) - would be very useful to show what you can do out of the box in a video-format when running your local node.

**Comment by zack-bitcoin** [comment]
Most users only use the light node.
I think it isn't good to spend too much time making full node setup videos.
Especially since these things change fast, and videos are hard to update.

**Comment by eolszewski** [comment]
I'm specifically advocating this for developers - what is the path that you
typically take to ensure that you haven't broken anything when developing?

With most applications I've worked on recently, we have live reloading and
runtime errors will display in the terminal. I haven't really cracked this
thing open yet - so I can't say much here, but it would be nice to include
that somewhere in the setup (if it exists).

**Comment by zack-bitcoin** [comment]
If the tests don't pass, then you broke something.

I don't see how a video would help.

**Comment by eolszewski** [comment]
What is your process for debugging and updating the software?

Update the code and run the tests - if they pass, then you're good to commit? I'm asking to see if there is CI in the project like [this](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#continuous-integration)

**Comment by zack-bitcoin** [comment]
start from README. you can read about how to run tests.
