### ISSUE TITLE
base64 decode / encode everything

### ISSUE THREAD

**Issue by Sykh** [zack-bitcoin/amoveo#194]
Since the "normal" outputs arent readable and some calls (all?) in the node need base64 decode of the given value, others i have to decode by hand or encode the result to use it somewhere else - can we settle on encoding every output and decoding every input where needed inside the node?

It's a bit annoying that the user has to do such thing - just run the values through the function if needed please

**Comment by zack-bitcoin** [comment]
I try to keep things in a format so that it is simple to verify the signatures and merkel proofs.
I don't want to maintain different code for verifying signatures of every different data structure.
