### ISSUE TITLE
different tx_hash in int and ext api

### ISSUE THREAD

**Issue by charlesmanson13** [zack-bitcoin/amoveo#207]
In internal api tx sender returns hash of unsigned tx
https://github.com/zack-bitcoin/amoveo/blob/88b5b7ab8f73de081592197cd2eb00105925e6c4/apps/amoveo_http/src/api.erl#L55
```
tx_maker0(Tx) -> 
    case sync_mode:check() of
	quick ->
	    S = "error, you need to be in sync mode normal to make txs",
	    io:fwrite(S),
	    ok;
	normal ->
	    case keys:sign(Tx) of
		{error, locked} -> 
		    io:fwrite("your password is locked. use `keys:unlock(\"PASSWORD1234\")` to unlock it"),
		    ok;
		Stx -> 
		    tx_pool_feeder:absorb(Stx),
		    hash:doit(Tx)
	    end
    end.
```
but external returns hash of tx with signature:
https://github.com/zack-bitcoin/amoveo/blob/88b5b7ab8f73de081592197cd2eb00105925e6c4/apps/amoveo_http/src/ext_handler.erl#L118
```
doit({txs, [Tx]}) ->
    ok = tx_pool_feeder:absorb([Tx]),
    {ok, hash:doit(Tx)};
```

**Comment by zack-bitcoin** [comment]
Thank you for finding this bug.
We do not want to include the signature inside the hash, that causes bugs like bitcoin. You can manipulate the bits of the signature without making it invalid.

**Comment by charlesmanson13** [comment]
Latest commit is wrong
https://github.com/zack-bitcoin/amoveo/blob/374fab92da6ccc062a00d9aafe3f553b4a49c7d2/apps/amoveo_http/src/api.erl#L55
Tx variable contains unsigned transaction, so execution fails on testnet_sign:data(Tx)
This line was correct before

**Comment by zack-bitcoin** [comment]
Thank you for saying this.
I fixed it just now.
