### ISSUE TITLE
Compiling failed

### ISSUE THREAD

**Issue by iDoka** [zack-bitcoin/amoveo#219]
I try to build last git
```
===> Compiling _build/default/lib/chalang/src/chalang.erl failed
_build/default/lib/chalang/src/chalang.erl:97: syntax error before: '{'
_build/default/lib/chalang/src/chalang.erl:115: syntax error before: '{'
```
How can I fix it?

**Comment by zack-bitcoin** [comment]
Compiling works fine.
Here is documentation on installing Amoveo and turning it on.
https://github.com/zack-bitcoin/amoveo/blob/master/docs/getting-started/turn_it_on.md

This error looks like your computer doesn't understand hash-maps. I guess you are using an old unsupported version of erlang. https://github.com/zack-bitcoin/chalang/blob/master/src/chalang.erl#L97

Maybe we should update chalang to be compatible with old versions of erlang.

**Comment by iDoka** [comment]
I use CentOS 7 x86_64 with:

Name        : erlang
Version     : R16B
Release     : 03.18.el7


```
$ erl -v
Erlang R16B03-1 (erts-5.10.4) [source] [64-bit] [smp:12:12] [async-threads:10] [hipe] [kernel-poll:false]
Eshell V5.10.4  (abort with ^G)
```

1. I cant find anywhere the requirement of minimal Erlang version for amoveo. 
2. I'm try to build the `amoveo-mining-pool` and `amoveo` is dependency. Could you issue the prebuild releases for  `amoveo-mining-pool` and `amoveo` ?
3. How to I should rewrite string `funs = #{},` for achieve compatibility to version R16B?

**Comment by zack-bitcoin** [comment]
https://github.com/zack-bitcoin/amoveo/blob/master/docs/getting-started/erlang_install.md

**Comment by zack-bitcoin** [comment]
Please share the steps for how to install on CentOS, I will add this to the documentation.

**Comment by iDoka** [comment]
I will try: 

```
wget http://packages.erlang-solutions.com/erlang-solutions-1.0-1.noarch.rpm
sudo rpm -Uvh erlang-solutions-1.0-1.noarch.rpm
sudo yum install erlang
```
check version:
```
$ erl -v
Erlang/OTP 21 [erts-10.2.3]
````


Next, according to https://github.com/zack-bitcoin/amoveo/blob/master/docs/getting-started/turn_it_on.md I run step by step:

`make prod-build` ===> release successfully created!
`make prod-go` -> /home/doka/amoveo/_build/prod/rel/amoveo_core/erts-10.2.3/bin/erl: line 13: /home/doka/amoveo/_build/prod/rel/amoveo_core/erts-10.2.3/bin/erlexec: Permission denied

should I run `make prod-go` under root or sudo?

**Comment by zack-bitcoin** [comment]
Amoveo should not be run as root, do not use sudo.

Do you have permission to the location where you are installing amoveo?

**Comment by iDoka** [comment]
My goal is run `amoveo-mining-pool`

**Comment by zack-bitcoin** [comment]
Maybe it is easier for you to rent a server that has Ubuntu installed
