### ISSUE TITLE
Not able to display addresses

### ISSUE THREAD

**Issue by Ouabi54** [zack-bitcoin/amoveo#22]
I have this error when i try to do a command which is available in documentation.
```
(ae_core_prod@Mbp)22> keys:address().
** exception error: undefined function keys:address/0
```

**Comment by zack-bitcoin** [comment]
That function does not exist.
Keys:pubkey ()
Is for displaying your pubkey. There are no addresses in Amoveo right now.

**Comment by Ouabi54** [comment]
Ok thank you, i will continue to test.

**Comment by zack-bitcoin** [comment]
ok, I got rid of every reference to keys:address().

**Comment by damoCl** [comment]
Have you decided on how addresses will be encoded and what elliptic curve to use.

**Comment by zack-bitcoin** [comment]
It is using the same curve as bitcoin for now.
I am displaying the entire uncompressed pubkey in base 64.
