### ISSUE TITLE
multiple payment send follwed by server crash

### ISSUE THREAD

**Issue by damoCl** [zack-bitcoin/amoveo#25]
Sending 10 multiple payments, in rapid succession from http://localhost:8081/main.html,  at block 298, to BJjOADT/mMg0BsqQkCDcEb/ylv6W85wipEKrY3qV5z3XvVrNygvVoEXsA6tncAoMuyvMB5Prepzqql3zZ1sDjjo=
seemed to crash the peer 146.185.142.103.

When i stopped the mining and executed "make prod-stop, and make-prod clean, then restarted, blocks synced back up  to block 130.

When I reset again, blocks started syncing to block 0, and proceeded to mine blocks 1,2,3 .... 

Potentially, my enthusiasm for some robust testing, caused a problem in the mempool at your end. The issue was replicated 8 hours beforehand.

Update: Blocks have re-synced back up to 270.  I suppose the more nodes on this network, the more stable it is.

**Comment by zack-bitcoin** [comment]
Thank you for running tests and reporting your progress.
I recently fixed a major error that was probably causing all the bugs you noticed.
The cpu was maxed at 100% the whole time.
