### ISSUE TITLE
Protocol 'inet_tcp': register/listen error

### ISSUE THREAD

**Issue by terrancewong** [zack-bitcoin/amoveo#254]
when launching , 

```
./_build/prod/rel/amoveo_core/bin/amoveo_core start
```

or 
```
make prod-restart
```
result:
```
Protocol 'inet_tcp': register/listen error
```

epmd daemon started.

Debian 9.9

**Comment by zack-bitcoin** [comment]
We don't have instructions for debian.
The documentation is for ubuntu.
VPS are cheap to rent by the hour if you want to try it out without installing, or you can run ubuntu in a virtual machine, or boot ubuntu up from a usb flash drive.

**Comment by terrancewong** [comment]
It is on a VPS.

I figured it out this is caused by iptables NAT POSTROUTING rules (for VPN server), deleting certain rules fixed it.

**Comment by zack-bitcoin** [comment]
Great. If you can install on debían,  please send me instructions so I can add it to the docs.

**Comment by terrancewong** [comment]
hmm, it's pretty simple, identical to Ubuntu.

**Comment by zack-bitcoin** [comment]
the ubuntu instructions use 'apt' extensively. 
I had thought that the `apt` software repository system was unavailable in debian.
