### ISSUE TITLE
Rounding error when sending through http://localhost:8081/main.html

### ISSUE THREAD

**Issue by damoCl** [zack-bitcoin/amoveo#26]
Sending .00104 tokens through http://localhost:8081/main.html, will be rounded to 103999

All other value [.00100 - .00117, step by .00001] checked out fine.

0.00207, 0.00208, 0.00209  will round to 206999 , 20799, 20899 , respectively.

OS : ubuntu  browser : firefox

**Comment by zack-bitcoin** [comment]
I think this has something to do with floating point in javascript.

**Comment by zack-bitcoin** [comment]
Thank you for sharing this report.
