### ISSUE TITLE
market completion gui

### ISSUE THREAD

**Issue by zack-bitcoin** [zack-bitcoin/amoveo#27]
When a market is concluded, we need to remove the buttons for canceling trades. COMPLETE
The explorer should stop displaying the market as active. COMPLETE
it should be convenient to settle the channel bets and take your winnings. <---- Still Needed

**Comment by cloggy45** [comment]
I will look into this, see if there is anything I can do.

**Comment by zack-bitcoin** [comment]
Great. Thank you cloggy.

I updated the instructions to clarify what is already completed.

This involves making a transaction, so take a look at this other file that is making a transaction: https://github.com/zack-bitcoin/amoveo/blob/master/apps/ae_http/priv/external_web/spend_tx.js

Here is the line of the integration test where we call the API that is used to settle the channel bets and take your winnings. https://github.com/zack-bitcoin/amoveo/blob/master/tests/test_market.py#L76

Good luck. Leave more questions in this thread if you feel lost.

**Comment by kein888** [comment]
Conekr

**Comment by zack-bitcoin** [comment]
GUI for the market was written long ago, and I forgot to close this issue.
