### ISSUE TITLE
GPU mining

### ISSUE THREAD

**Issue by zack-bitcoin** [zack-bitcoin/amoveo#28]
We need software to make it easy to mine Amoveo with a GPU.
We also need instructions on how to set the miner up.

**Comment by cuanhne** [comment]
Leave a comment

**Comment by ni-om** [comment]
Now as we have mainnet launch date... no GPU mining still?

**Comment by zack-bitcoin** [comment]
Still no gpu mining.
Hopefully we will have it soon.

**Comment by okdoomfist** [comment]
Can probably close this

**Comment by zack-bitcoin** [comment]
There are now many competing GPU miner projects, so this issue is solved.
