### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by damoCl** [zack-bitcoin/amoveo#30]
Mining crashed on block 803. On Block 802, I made a channel on localhost:8081/main.html. of 500 tokens. Block chain seems to be reset from block zero.

**Comment by zack-bitcoin** [comment]
Hi damoCI.
Yes, I accidentally deleted the blocks from the server.
If you still have them, please share them.
I got it fixed now.

**Comment by zack-bitcoin** [comment]
yes, thanks for sharing the error.
It is ok, we can mine the blocks again.
