### ISSUE TITLE
Progress report on Oracle technology - no mention of spectre.ai

### ISSUE THREAD

**Issue by markcross** [zack-bitcoin/amoveo#33]
https://github.com/zack-bitcoin/amoveo/blob/master/docs/progress_reports/22_november_2017.md

No mention of spectre.ai are you waiting for it to open source?

Cheers Mark

**Comment by zack-bitcoin** [comment]
Good idea.

https://github.com/zack-bitcoin/amoveo/blob/master/docs/progress_reports/december_2017.md
I added them to the December progress report.

Cheers
