### ISSUE TITLE
Progress Reports : Where do you place spectre.ai on this chart

### ISSUE THREAD

**Issue by markcross** [zack-bitcoin/amoveo#34]
Zack,

Where do you place spectre.ai on this chart or they the wrong part of the food chain?

Cheers Mark

[Where do you place spectre.ai on this chart](https://github.com/zack-bitcoin/amoveo/blob/master/docs/progress_reports/22_november_2017.md)

**Comment by zack-bitcoin** [comment]
That chart is old.
spectre.ai is in the new chart for December. https://github.com/zack-bitcoin/amoveo/blob/master/docs/progress_reports/december_2017.md
