### ISSUE TITLE
Full node issues after running c-miner for a period of time

### ISSUE THREAD

**Issue by majordutch** [zack-bitcoin/amoveo#35]
When running the c-miner locally on my full node, it runs as expected, eventually finds a block, then randomly stops and produces an error.

On the full node output, I get the following message, about 10 times in a very quick fashion (<2 seconds):
```
got this data
["mining_data"]
```

After the 10th or so message, the c-miner will return the following error:
```
cannot connect to server** exception error: no match of right hand side value 2
     in function  miner:talk_helper/3 (miner.erl, line 68)
     in call from miner:start2/0 (miner.erl, line 36)
```

If I try to restart mining, I will get the same sequence of events, immediately. 

Additionally, if I stop the full node properly and restart it (without deleting the database), then run "sync:start().", I get the following output:

```
(ae_core_prod@amoveo-node-01)1> sync:start().
ok
(ae_core_prod@amoveo-node-01)2> false 3
tx_pool_feeder died
```

Running the miner will produce the same sequence of events as explained above, immediately.

I hope this is helpful, if I can provide further detail, please let me know.

**Comment by majordutch** [comment]
Following up on this, I let the c-miner run for a while, probably solved about 6 or 7 blocks with no issues. I think I solved those blocks sequentially (no other miners).

I wonder if there is some sort of race condition that occurs if a block is solved by another miner in between the getwork calls? It's only a thought... Like I said happy to provide further detail and/or try and reproduce again.

**Comment by skergetd** [comment]
Hi,when did you run your tests? I was testing a bit and running web miner from around 23UTC-2UTC...might this be the case?

**Comment by zack-bitcoin** [comment]
Thanks for sharing this. I will do testing to try to reproduce this error.

**Comment by zack-bitcoin** [comment]
This error was fixed at some point in the last 2 weeks. I will close it now.
