### ISSUE TITLE
packer.erl missing(?)

### ISSUE THREAD

**Issue by jeeiantam** [zack-bitcoin/amoveo#37]
When I try to run sync:start(). , the following error is thrown : 

sync with peer ** exception error: undefined function packer:pack/1
     in function  sync:start/1 (/home/***/Amoveo/amoveo/_build/prod/lib/ae_core/src/consensus/sync.erl, line 50)

Looking at the history, it might be because src/consensus/packer.erl is missing.

**Comment by zack-bitcoin** [comment]
Packer.pack isn't missing. It is a part of the encryption dependency.

I am not sure how you managed to run the code without the dependencies, since they install automatically in the makefile using rebar. 

Maybe you are running a version of the code that you downloaded like 2 months ago?

**Comment by jeeiantam** [comment]
I was using an old release, deleting the amoveo directory and re-syncing solved the issue.

Thanks!
