### ISSUE TITLE
The invitation

### ISSUE THREAD

**Issue by kaidiren** [zack-bitcoin/amoveo#39]
hi, I want invate you to  https://github.com/amoveo-org as admin role, it named amoveo-org temporarily  If you have a preferred name,  we can rename it. feel for free. if you do not want to do this, it's also ok. 

😊

**Comment by zack-bitcoin** [comment]
I already have an organization like this.
I am in the process of getting rid of it.
I find that it makes a mess, I like it better to keep my code in one place.

**Comment by kaidiren** [comment]
ok,  i will delete that org
