### ISSUE TITLE
Why amoveo decided to go with SHA256 Proof of Work?

### ISSUE THREAD

**Issue by nurazhar** [zack-bitcoin/amoveo#47]
Is it because of Veo initial distribution issues? I mean ethereum is moving to PoS and [Chia](chia.network) is working on [PoST](https://eprint.iacr.org/2017/893)

**Comment by zack-bitcoin** [comment]
Amoveo is an experiment in putting financial derivatives inside state channels.
This goal is already big enough.
PoS is outside the scope of this project.

**Comment by zack-bitcoin** [comment]
You are right about Veo distribution.
PoW is the ideal method of distributing the coins. 
It is much more efficient than an ICO.
