### ISSUE TITLE
Trying to run fullnode - died

### ISSUE THREAD

**Issue by nurazhar** [zack-bitcoin/amoveo#49]
![screenshot from 2018-01-02 20-44-17](https://user-images.githubusercontent.com/31495752/34484161-d7c3fbd2-effd-11e7-905b-8c91776bd01f.png)

**Comment by zack-bitcoin** [comment]
Thank you for sharing this report.

There are a couple of problems here.
First off, this is an invalid command: `sync:start()`
Instead it should be written this way: `sync:start().`
Commands in the erlang prompt need to end in a period. `.`

The next problem is that the server died, so you cannot connect to it.
This is my fault. I am glad you warned me the server had died.
I will fix this soon.

**Comment by zack-bitcoin** [comment]
It is fixed.

The problem was that after the difficulty increased at block 2000, the miner's memory leak became an issue that eventually made the database corrupted at height 2138.
I fixed the memory leak, and re-synced from the genesis. It is working now.
