### ISSUE TITLE
Full node sync failed.

### ISSUE THREAD

**Issue by esrever10** [zack-bitcoin/amoveo#53]
![image](https://user-images.githubusercontent.com/1320907/34680593-800517ce-f4d4-11e7-81e3-c6962c8a4f30.png)

**Comment by zack-bitcoin** [comment]
maybe you are using an old version of the code?
It is changing quickly every day.
And recently some dependencies changed, so a simple "git pull" wont get all the changes.

**Comment by hyunjongL** [comment]
I guess I'm having the same problem. Mine absorbed 24blocks and now block absorber dies and sync dies.
Ubuntu 16.04 and just cloned the repo

**Comment by esrever10** [comment]
@zack-bitcoin Thank you. Now I rebuild and restart, it works.  Before this I did the same, but it did not work, may be some problem in my environment.
