### ISSUE TITLE
Sync and Keys Question

### ISSUE THREAD

**Issue by hyunjongL** [zack-bitcoin/amoveo#55]
So my sync keeps stopping at block 499
Is this because I am using a wifi? or because I am using a institutional network?
It is very wierd.
Also, can anyone help me to parse the keys into human readable form? I found the keys.db.

**Comment by zack-bitcoin** [comment]
To see your pubkey from the erlang terminal:
`Api:pubkey().`

I think the server only has 499 blocks right now.

**Comment by zack-bitcoin** [comment]
I looked into this more.
It looks like the server's database got corrupted 3 days ago, so I am restarting it.
