### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by g0ldeng0d** [zack-bitcoin/amoveo#56]
Hi Zack.  I'm testing out the light wallet...

http://159.89.106.253:8080/wallet.html

I'm able to mine blocks but from time to time (seems a random occurrence) get the following error.

_Failed to load http://159.89.106.253:8085/: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://159.89.106.253:8080' is therefore not allowed access. The response had HTTP status code 500._

OSX 10.13.2. Chrome Version 63.0.3239.132 (Official Build) (64-bit)

Screen shot: https://imgur.com/a/iCaqB

Hope this helps!

**Comment by zack-bitcoin** [comment]
Thank you for sharing this.
Most of the miners are tuned to operate efficiently if the block time is about 10 minutes.
The difficulty is pretty low now, so maybe someone else was mining at the same time, and they found blocks in much less time than 10 minutes.
In that case, your javascript miner would be mining on stale data most of the time, and the server would give this kind of error every time you publish invalid work.

Or maybe I tuned it poorly, and the mining pool is updating the work more frequently than javascript checks if the work has been updated.

**Comment by Mandelhoff** [comment]
I was running the C miner yesterday for a few hours, so a concurrent miner sounds likely. Good diagnoses.

**Comment by okdoomfist** [comment]
Browser miner is obsolete, suggest close.

**Comment by zack-bitcoin** [comment]
thank you okdoomfist
