### ISSUE TITLE
Check Balance Functionality in Light Wallet

### ISSUE THREAD

**Issue by g0ldeng0d** [zack-bitcoin/amoveo#57]
Hi Zack. Again, testing out the wallet...

http://159.89.106.253:8080/wallet.html

OSX 10.13.2. Chrome Version 63.0.3239.132 (Official Build) (64-bit)

I click on "Check Balance" and nothing happens.

Here's an error message in the console...

![screen shot 2018-01-15 at 3 36 48 pm](https://user-images.githubusercontent.com/5373393/34960700-f1ab00e8-fa09-11e7-8449-44ce2931e321.png)

I checked my balance using the explorer URL below (I guessed it based on the new IP) and it says "not a number".  NaN

http://159.89.106.253:8080/explorer.html

![screen shot 2018-01-15 at 3 41 01 pm](https://user-images.githubusercontent.com/5373393/34960817-84020b1c-fa0a-11e7-93ce-9fc277282f62.png)

Hope this helps!

**Comment by g0ldeng0d** [comment]
Update: I did a hard refresh (same private key) and got this error...

![screen shot 2018-01-15 at 4 06 45 pm](https://user-images.githubusercontent.com/5373393/34961646-27ddaad6-fa0e-11e7-8b07-5c4b3d956320.png)

**Comment by zack-bitcoin** [comment]
I tested both these things right now. I can check by balance in both correctly.

It looks like you don't have any coins.
You can mine some, or you can leave your pubkey here and I will send you some.

**Comment by g0ldeng0d** [comment]
Thanks... I'll keep poking around tomorrow.

BNo1Kp1lHLEBId0KJb+Z/v5yIYmfDdHfXK22hDxQDXW6osQy0frmsVzGwdV+na2FLRL1m2WihZsfskvXP1GsLxM=

**Comment by Schebesta** [comment]
I too can't get it to load. Or am I seeing it the balance and I dont realise it?

BIjqwjTU4981y4aHnGPiik9XvGATkjlJXVaUQqAWWjdS+Pc9JybhP1gL82hDe7JPr0zZTlLvmYpEF+Wjtj9VOgM=
