### ISSUE TITLE
Light Wallet Create Account Function

### ISSUE THREAD

**Issue by g0ldeng0d** [zack-bitcoin/amoveo#58]
Hi again Zack!  Using the light wallet...

http://159.89.106.253:8080/wallet.html

Tried the "create account" function...

![screen shot 2018-01-15 at 3 42 40 pm](https://user-images.githubusercontent.com/5373393/34960889-d61411a2-fa0a-11e7-94ef-0c404be36c9e.png)

Got the following error...

![screen shot 2018-01-15 at 3 42 32 pm](https://user-images.githubusercontent.com/5373393/34960896-da6a6ecc-fa0a-11e7-8c04-62c1424d627f.png)

Let me know what I can do here to follow up with better info.

**Comment by zack-bitcoin** [comment]
You need to have enough money in order to afford to give money to someone. Including the transaction fee.
There are not 1000 coins in the entire testnet right now.
I turned the block reward low, so there is less than 1 coin mined so far.
