### ISSUE TITLE
Continuous Node Sync with out Public IP

### ISSUE THREAD

**Issue by Mandelhoff** [zack-bitcoin/amoveo#73]
I stood my node up and did a sync:start(). That worked. Someone is mining, and the http://159.89.106.253:8080/wallet.html is showing increasing height. My node doesn't appear to be picking up the increased block heights until I type sync:start(). again.

If I call sync:start()., it does seem to go get the new blocks that 159.89.106.253 knows about. Is there something I need to do to get my node continuously sync?

![image](https://user-images.githubusercontent.com/35471470/35393456-a436c164-01aa-11e8-89c3-08790c12554e.png)

**Comment by g0ldeng0d** [comment]
That might be me... but when I try to mine and get "connection refused" errors.

![err](https://user-images.githubusercontent.com/5373393/35393674-a6d79af2-01b3-11e8-8b4d-a20d2f35656a.png)

**Comment by Mandelhoff** [comment]
Whoever is mining is going really fast. They got 20 blocks in ~5 minutes (from ~134 to ~154).

I turned on my miner and found a block around 149. I think it failed to pay my miner, because my account was locked - but my node balance didn't increase after the block was found. Perhaps, my found block was thrown out because my node isn't syncing with the other node that is mining very fast.

![image](https://user-images.githubusercontent.com/35471470/35393957-0bb73a20-01ac-11e8-97d3-b2aa505be343.png)

**Comment by zack-bitcoin** [comment]
If you add yourself tor the list of peers, then the other nodes in the network should push new blocks to you.

It is more efficient to recieve blocks that are pushed instead of repeatedly checking if there are new blocks.
This way there are less network messages, and we learn about new blocks more quickly. 


But not all computers have an externally accessible port. So your suggestion is good. I will add a way to sync continuously.

**Comment by Mandelhoff** [comment]
Looks like this command might be the add myself to peers list. Is that correct?
api:add_peer(IP, Port).

I'll have to open port 8080, which is fine for my Azure VM. Did you say something like that is unsafe back when I was asking questions about the miner running on port 8085?

**Comment by zack-bitcoin** [comment]
Sounds good.

The program should not expose and bad ports, even if you tell your VM to expose them.
The internal port only accepts connections from the same computer.

**Comment by Mandelhoff** [comment]
Ok, sounds like no security problem opening port 8080 and adding peer. I'll do that.

**Comment by Mandelhoff** [comment]
I ran api:add_peer for over an hour when at least one other person was mining. It seemed to be working well. My mined blocks were being counted in the 159.x.x.x node, and my node was keeping sync with blocks that others were mining in to the 159.x.x.x node.

Will keep this issue open for "Continuous Node Sync without Public IP" tracking. Updated issue title.

**Comment by zack-bitcoin** [comment]
Great! thank you for testing this out, I am glad it is working.

**Comment by zack-bitcoin** [comment]
I pushed some changes today so now it automatically syncs while you are mining.
