### ISSUE TITLE
Keys Unlock on Amoveo Node

### ISSUE THREAD

**Issue by Mandelhoff** [zack-bitcoin/amoveo#74]
I did a keys restore on my node.

I copied my keys.db up to the new node here while the node was stopped.
/amoveo/_build/prod/rel/ae_core/keys/keys.db

Then, I did make prod-go. The api:balance(). shows a balance value that looks correct. I can't seem to unlock the keys to spend funds to pay miners.

I tried keys:unlock("password"). as the text suggests. I also tried "PASSWORD1234" and a password value that I used on my previous node. I wrote it down, so I'm pretty sure it's correct. (I redacted my real key password in red.)

Am I doing something wrong or is this maybe a bug?
Thank you.

![image](https://user-images.githubusercontent.com/35471470/35394495-86a82932-01ad-11e8-8588-b1e9104b2811.png)

**Comment by zack-bitcoin** [comment]
The default password is "". An empty string.

There are commands for changing your password.

**Comment by Mandelhoff** [comment]
That worked. Thank you - 

unlock:keys("").
