### ISSUE TITLE
api:add_peer broke sync?

### ISSUE THREAD

**Issue by Mandelhoff** [zack-bitcoin/amoveo#76]
I ran api:add_peer on my node, and now it won't sync. Height is locally 201 and current height on your node is 423.

Is there something I can do to fix this? Thank you.

![image](https://user-images.githubusercontent.com/35471470/35409058-c58e45ae-01d6-11e8-903f-754f6c5e75c8.png)

**Comment by Mandelhoff** [comment]
The IP address in the redacted box is my Azure VM address. The [-6, ...] redacted line contains the address value in decimal form, so I redacted that too. Noting this in case I was supposed to add your 159.x.x.x in the peer address instead of my node's public address.

**Comment by zack-bitcoin** [comment]
It looks like the Api add peer command had bad inputs. 
You used strings instead of numbers.

Here is an example of how to format it.
https://github.com/zack-bitcoin/amoveo/blob/master/Makefile#L200

There is a command to dump everything from the list of peers:
 peers:dump().

**Comment by Mandelhoff** [comment]
I got api:add_peer to work. Adding the invalid peer seemed to make my sync broken, so I had to do a fresh clone.

peers:dump(). didn't appear to work though.

![image](https://user-images.githubusercontent.com/35471470/35412213-14845e82-01e1-11e8-97f7-403f6779ddfe.png)

**Comment by zack-bitcoin** [comment]
yes, my mistake. peers:dump() isn't real.
There is a command `peers:remove(Peer)` which removes a single peer
