### ISSUE TITLE
tx_pool_feeder died - Miner payouts failing?

### ISSUE THREAD

**Issue by Mandelhoff** [zack-bitcoin/amoveo#77]
I was doing some mining, and thought I was noticing my miner wasn't always paid when a block was found.

I don't see anything unusual on the pool and miner console messages, but I saw "tx_pool_feeder died" right after some (but not all) of the node spend messages that indicate miner payouts.

I think the node is getting the block reward. The node balance is going up across block finds, but the payout seems to fail occasionally.

![image](https://user-images.githubusercontent.com/35471470/35462467-b5d9eede-02b1-11e8-8c8a-37374a1829e6.png)

**Comment by zack-bitcoin** [comment]
I pushed some changes today that should make mining work better. I hope this solves your problem.
