### ISSUE TITLE
Sync:start(). weird response and fail

### ISSUE THREAD

**Issue by Mandelhoff** [zack-bitcoin/amoveo#78]
Just for tracking, this is the screenshot from when I ran sync to send blocks back to your node. It looks like everything worked fine, but my node gave a bunch of these warning messages:

Please close this if you don't need this for tracking.

![image](https://user-images.githubusercontent.com/35471470/35464845-d96c7da6-02bd-11e8-8c89-1335e8192a60.png)

**Comment by zack-bitcoin** [comment]
Yes, there are some issues with pushing large amounts of blocks.

Pushing more than 1 block at a time has never been an important goal.
It is not something we need for the blockchain to work.
