### ISSUE TITLE
Make Bet Error

### ISSUE THREAD

**Issue by Mandelhoff** [zack-bitcoin/amoveo#82]
I loaded up my channel state and tried to make a bet. (I'm not sure if this is related to channel state loading or not.) This was after I had successfully made bets on this same channel.

Screenshots of the errors:

![image](https://user-images.githubusercontent.com/35471470/35629212-a9b44f40-0663-11e8-945f-e1a98e9678bb.png)

![image](https://user-images.githubusercontent.com/35471470/35629223-abb056ae-0663-11e8-8fbc-cd4f1fcc965d.png)

**Comment by zack-bitcoin** [comment]
If you want to see your channel balance, the channel tx must have been included in a block.

Since the merkle proof library is saying that the trie doesn't contain your channel.

**Comment by Mandelhoff** [comment]
Sounds right - I mined a few blocks and then loading my channel from text file worked.
