### ISSUE TITLE
Bet Settling and Combining Bet Errors

### ISSUE THREAD

**Issue by Mandelhoff** [zack-bitcoin/amoveo#84]
I clicked the "check if any bets have been settled" button, and got a "this channel has been closed" error.

I clicked the "combine bets in opposite..." button, and got a server 500 error.

![image](https://user-images.githubusercontent.com/35471470/35634122-849cab00-0670-11e8-8af7-f8e27bd67a35.png)

**Comment by zack-bitcoin** [comment]
matching bets, and combine-canceling bets should be working again after the recent pull request.
