### ISSUE TITLE
Incorrect Display String on Bet Form

### ISSUE THREAD

**Issue by Mandelhoff** [zack-bitcoin/amoveo#89]
"Amount to lock in channel" should be something about the amount of the Bet instead of being channel related:

![image](https://user-images.githubusercontent.com/35471470/35706854-035d5154-076d-11e8-8981-bcbfe8cf17b1.png)

**Comment by zack-bitcoin** [comment]
yes, you are right.

**Comment by zack-bitcoin** [comment]
ok, I fixed it.
