### ISSUE TITLE
Node crashes on start

### ISSUE THREAD

**Issue by Mandelhoff** [zack-bitcoin/amoveo#92]
Within the last 30 min, I did a rm -rf amoveo and cloned a fresh copy. It built fine and ran. I turned it off with api:off(). and halt().

The screenshot shows the fail to start twice. It is failing to start back up with this error:

![image](https://user-images.githubusercontent.com/35471470/35826664-ffe2be8c-0a7e-11e8-854a-1740b420de71.png)

**Comment by zack-bitcoin** [comment]
I think there was a short period of time when I had pushed broken code here.
But I just tested the most recent version of the code, and it is working correctly.
I turned it  on, synced a few blocks, turned if off, turned it on, synced a few blocks. 
Everything seems normal.

if you do `sync_mode:quick().` then it downloads blocks faster. but you have to change it back with `sync_mode:normal().` after you finish downloading the blocks.

**Comment by Mandelhoff** [comment]
Ok, I'll try again. Is just calling sync:start(). fine too? That's what I've been doing to get my api:height(). correct.

Is there any "correct time" to do the add_peer? Not sure if that might interfere with the sync.

**Comment by zack-bitcoin** [comment]
any time should be fine to add_peer.
