### ISSUE TITLE
Miner.js speed calc

### ISSUE THREAD

**Issue by Mandelhoff** [zack-bitcoin/amoveo#96]
https://github.com/zack-bitcoin/amoveo/blob/6781b16a36fcafb1072d4a55c27e9e45194a8a76/apps/ae_http/priv/external_web/miner.js#L45

Should the miner.js speed calc be "1000 / d" instead of "10000 / d"?

I'm not 100% sure, so I didn't open a pull request for that change.

**Comment by zack-bitcoin** [comment]
You are correct. Thank you for noticing.
I rewrote it to use more variables and better variable names, I will push the changes after testing.

**Comment by zack-bitcoin** [comment]
I pushed the fix. 
I haven't yet updated the server for this change.

**Comment by zack-bitcoin** [comment]
ok, now I updated the server.
